import { test, expect } from '@playwright/test';

test('Genera Licenza SIAE', async ({ page }) => {
  await page.getByRole('link', { name: 'SIAE SIAE.it https://www.siae' }).click();
  await page.getByRole('button', { name: 'Accedi' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('david.azzato@libero.it');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('!7rFiW#.rV3t5Xg');
  await page.getByRole('button', { name: 'Accedi' }).click();
  await page.locator('#GOAL_STD').getByRole('button', { name: 'Accedi' }).click();
  await page.getByRole('button', { name: 'Calcola Licenza' }).click();
  await page.getByText('Download', { exact: true }).click();
  await page.getByRole('img', { name: 'icona_servizio' }).first().click();
  await page.locator('#section_download_servizi').getByText('Seleziona').nth(2).click();
  await page.getByRole('textbox', { name: 'gg/mm/aaaa' }).click();
  await page.getByRole('link', { name: '18' }).click();
  await page.getByRole('button', { name: 'SI' }).click();
  await page.locator('#download_extend_streaming > .container > div:nth-child(2) > div > .col-md-12 > .col-md-5 > .col-md-7 > .seleziona_button_servizi > span').first().click();
  await page.locator('#download_extend_streaming > .container > div:nth-child(2) > div:nth-child(2) > .col-md-12 > div > .col-md-4 > .seleziona_button_servizi > span').click();
  await page.locator('#download_extend_streaming > .container > div:nth-child(2) > div > .col-md-12 > div > .col-md-4 > .seleziona_button_servizi > span').first().click();
  await page.locator('#section_download_social_network #social_twitter').getByRole('img', { name: 'icona_social' }).click();
  await page.getByRole('button', { name: 'Prosegui' }).click();
  await page.locator('#select2-l60w-container').click();
  await page.getByRole('treeitem', { name: 'Web' }).click();
  await page.locator('#row_data_section_MDWL').getByRole('combobox', { name: 'Seleziona' }).locator('span').nth(1).click();
  await page.getByRole('treeitem', { name: 'Gratis' }).click();
  await page.locator('#row_data_section_SG').getByRole('combobox', { name: 'Seleziona' }).locator('span').nth(1).click();
  await page.getByRole('treeitem', { name: 'SITI DI ORGANIZZAZIONI O' }).click();
  await page.locator('#select2-c7cg-container').click();
  await page.getByRole('treeitem', { name: 'Gratis' }).click();
  await page.locator('#select2-6uqu-container').click();
  await page.getByRole('treeitem', { name: 'Oltre' }).click();
  await page.locator('#select2-1f0e-container').click();
  await page.getByRole('treeitem', { name: 'SITI COMMERCIALI O' }).click();
  await page.locator('#select2-c73f-container').click();
  await page.getByRole('treeitem', { name: 'Intro/Outro' }).click();
  await page.locator('#select2-9wm7-container').click();
  await page.getByRole('treeitem', { name: 'SITI INTESTATI A PERSONA' }).click();
  await page.locator('#select2-7yc3-container').click();
  await page.getByRole('treeitem', { name: 'Artista Interprete' }).click();
  await page.locator('#select2-jzuh-container').click();
  await page.getByRole('treeitem', { name: 'Vai a calcola' }).click();
  await page.locator('#section_download_importo_licenza span').first().click();
  await page.getByRole('button', { name: 'Calcola', exact: true }).click();
  await page.getByText('Totale: € 6.954,00 IVA inclusa').click();
  await page.getByRole('button', { name: 'Genera' }).click();
});